"""
High-level Docker operations for MultiCord bot lifecycle management.

This module provides Docker operations like Dockerfile generation, image building,
container creation/management, and log streaming for Discord bots.
"""

import os
import re
import logging
from pathlib import Path
from typing import Optional, Dict, List, Generator
from datetime import datetime

import docker
from docker.errors import APIError, ImageNotFound, NotFound
from docker.models.containers import Container
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn

from .docker_client import DockerClient, DockerConnectionError

logger = logging.getLogger('multicord.docker.manager')
console = Console()


class DockerBuildError(Exception):
    """Raised when Docker image build fails."""
    pass


class DockerManager:
    """
    Manages Docker operations for MultiCord bots.

    Handles Dockerfile generation, image building, container lifecycle,
    and integrates with MultiCord's bot directory structure.
    """

    def __init__(self, bots_dir: Optional[Path] = None):
        """
        Initialize Docker manager.

        Args:
            bots_dir: Path to bots directory (default: ~/.multicord/bots)
        """
        if bots_dir is None:
            bots_dir = Path.home() / ".multicord" / "bots"

        self.bots_dir = Path(bots_dir)
        self.docker_client = DockerClient()

        # Ensure Docker network exists
        try:
            self.docker_client.ensure_network()
        except DockerConnectionError as e:
            logger.error(f"Docker initialization failed: {e}")
            raise

    def generate_dockerfile(self, bot_path: Path) -> str:
        """
        Auto-generate Dockerfile from bot template and dependencies.

        Analyzes bot's requirements.txt to detect Python version and
        generates a multi-stage Dockerfile with best practices.
        Uses detect_entry_point() to resolve the correct bot file.

        Args:
            bot_path: Path to bot directory

        Returns:
            Generated Dockerfile content as string

        Raises:
            ValueError: If bot directory or requirements.txt not found
        """
        if not bot_path.exists():
            raise ValueError(f"Bot directory not found: {bot_path}")

        requirements_file = bot_path / "requirements.txt"
        if not requirements_file.exists():
            raise ValueError(f"requirements.txt not found in {bot_path}")

        # Detect Python version from requirements or use default
        python_version = self._detect_python_version(bot_path)

        # Detect bot entry point (manifest-first, then convention)
        from multicord.utils.bot_detector import detect_entry_point
        entry_point = detect_entry_point(bot_path)

        # Read requirements
        with open(requirements_file, 'r', encoding='utf-8') as f:
            requirements = f.read().strip()

        # Generate multi-stage Dockerfile
        dockerfile = f'''# Multi-stage Dockerfile for MultiCord Discord bot
# Generated by MultiCord CLI

# Stage 1: Builder
FROM python:{python_version}-slim as builder

# Set working directory
WORKDIR /build

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    g++ \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Stage 2: Runtime
FROM python:{python_version}-slim

# Create non-root user for security
RUN useradd --create-home --shell /bin/bash multicord

# Set working directory
WORKDIR /app

# Copy Python dependencies from builder
COPY --from=builder /root/.local /home/multicord/.local

# Copy bot files
COPY --chown=multicord:multicord . /app

# Create necessary directories
RUN mkdir -p /app/logs /app/data && \\
    chown -R multicord:multicord /app

# Switch to non-root user
USER multicord

# Set environment variables
ENV PATH=/home/multicord/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1

# Health check (ping bot process)
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
  CMD ps aux | grep -q "[p]ython.*{entry_point}" || exit 1

# Run bot
CMD ["python", "{entry_point}"]
'''

        logger.info(f"Generated Dockerfile for {bot_path.name} (Python {python_version})")
        return dockerfile

    def _detect_python_version(self, bot_path: Path) -> str:
        """
        Detect Python version from bot's configuration or requirements.

        Args:
            bot_path: Path to bot directory

        Returns:
            Python version string (e.g., "3.11")
        """
        # Check if there's a python-version file
        version_file = bot_path / ".python-version"
        if version_file.exists():
            version = version_file.read_text().strip()
            if re.match(r'^\d+\.\d+', version):
                return version[:4]  # Return major.minor (e.g., "3.11")

        # Check requirements.txt for python_requires
        requirements_file = bot_path / "requirements.txt"
        if requirements_file.exists():
            content = requirements_file.read_text()
            match = re.search(r'python[_-]?requires?\s*[=><!]+\s*["\']?(\d+\.\d+)', content, re.IGNORECASE)
            if match:
                return match.group(1)

        # Default to Python 3.11 (current stable for Discord.py)
        logger.debug("Using default Python version: 3.11")
        return "3.11"

    def build_image(
        self,
        bot_path: Path,
        tag: Optional[str] = None,
        show_progress: bool = True
    ) -> str:
        """
        Build Docker image for bot.

        Args:
            bot_path: Path to bot directory
            tag: Image tag (default: multicord/{bot_name}:latest)
            show_progress: Show build progress (default: True)

        Returns:
            Image ID

        Raises:
            DockerBuildError: If image build fails
        """
        bot_name = bot_path.name
        if tag is None:
            # Docker tags must be lowercase
            tag = f"multicord/{bot_name.lower()}:latest"

        logger.info(f"Building Docker image for '{bot_name}' as '{tag}'")

        try:
            # Generate Dockerfile
            dockerfile_content = self.generate_dockerfile(bot_path)

            # Write Dockerfile to bot directory
            dockerfile_path = bot_path / "Dockerfile"
            with open(dockerfile_path, 'w', encoding='utf-8') as f:
                f.write(dockerfile_content)

            # Build image with progress
            if show_progress:
                image_id = self._build_with_progress(bot_path, tag)
            else:
                image, build_logs = self.docker_client.client.images.build(
                    path=str(bot_path),
                    tag=tag,
                    rm=True,  # Remove intermediate containers
                    forcerm=True  # Always remove intermediate containers
                )
                image_id = image.id

            logger.info(f"✓ Built image: {tag} ({image_id[:12]})")
            console.print(f"[green]✓ Image built successfully: {tag}[/green]")

            return image_id

        except APIError as e:
            error_msg = f"Failed to build Docker image: {e}"
            logger.error(error_msg)
            console.print(f"[red]✗ {error_msg}[/red]")
            raise DockerBuildError(error_msg)

    def _build_with_progress(self, bot_path: Path, tag: str) -> str:
        """Build Docker image with progress display."""
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TaskProgressColumn(),
            console=console
        ) as progress:
            task = progress.add_task(f"Building {tag}...", total=None)

            # Build with low-level API for streaming
            response = self.docker_client.client.api.build(
                path=str(bot_path),
                tag=tag,
                rm=True,
                decode=True
            )

            image_id = None
            for chunk in response:
                if 'stream' in chunk:
                    stream_text = chunk['stream'].strip()
                    if stream_text:
                        progress.update(task, description=f"Building: {stream_text[:60]}")

                if 'aux' in chunk and 'ID' in chunk['aux']:
                    image_id = chunk['aux']['ID']

                if 'error' in chunk:
                    raise DockerBuildError(chunk['error'])

            if image_id is None:
                # Fallback: get image by tag
                image = self.docker_client.client.images.get(tag)
                image_id = image.id

            return image_id

    def create_container(
        self,
        bot_name: str,
        image_id: str,
        instance_id: int = 1,
        env_vars: Optional[Dict[str, str]] = None,
        resource_limits: Optional[Dict[str, any]] = None
    ) -> str:
        """
        Create container instance from image.

        Args:
            bot_name: Bot name
            image_id: Docker image ID or tag
            instance_id: Instance number for multi-container scaling (default: 1)
            env_vars: Environment variables dict (default: loads from bot's .env)
            resource_limits: Resource limits dict with 'cpus' and 'memory' keys

        Returns:
            Container ID

        Raises:
            APIError: If container creation fails
        """
        # Docker container names should be lowercase for consistency
        container_name = f"multicord_{bot_name.lower()}_{instance_id}"
        bot_path = self.bots_dir / bot_name

        logger.info(f"Creating container: {container_name}")

        # Load environment variables from bot's .env if not provided
        if env_vars is None:
            env_vars = self._load_bot_env(bot_path)

        # Add instance ID to environment
        env_vars['BOT_INSTANCE_ID'] = str(instance_id)
        env_vars['BOT_NAME'] = bot_name

        # Prepare resource limits
        mem_limit = None
        nano_cpus = None
        if resource_limits:
            if 'memory' in resource_limits:
                mem_limit = resource_limits['memory']  # e.g., "512m", "1g"
            if 'cpus' in resource_limits:
                # Convert to nano CPUs (1 CPU = 1e9 nano CPUs)
                nano_cpus = int(resource_limits['cpus'] * 1e9)

        try:
            # Create container with volumes for logs and data
            container = self.docker_client.client.containers.create(
                image=image_id,
                name=container_name,
                environment=env_vars,
                volumes={
                    str(bot_path / "logs"): {'bind': '/app/logs', 'mode': 'rw'},
                    str(bot_path / "data"): {'bind': '/app/data', 'mode': 'rw'}
                },
                network="multicord-network",
                mem_limit=mem_limit,
                nano_cpus=nano_cpus,
                detach=True,
                labels={
                    "managed-by": "multicord",
                    "bot-name": bot_name,
                    "instance-id": str(instance_id)
                }
            )

            logger.info(f"✓ Created container: {container_name} ({container.id[:12]})")
            return container.id

        except APIError as e:
            logger.error(f"Failed to create container: {e}")
            raise

    def create_sharded_containers(
        self,
        bot_name: str,
        image_id: str,
        shard_count: int,
        resource_limits: Optional[Dict[str, any]] = None
    ) -> List[str]:
        """
        Create multiple containers for Discord sharding.

        Each shard runs in its own container with a unique SHARD_ID environment
        variable. Discord.py's AutoShardedBot automatically handles guild distribution
        across shards using: guild_id % shard_count.

        Args:
            bot_name: Bot name
            image_id: Docker image ID or tag
            shard_count: Total number of shards to create (1-16 recommended)
            resource_limits: Optional resource limits dict with 'cpus' and 'memory' keys

        Returns:
            List of container IDs (one per shard)

        Raises:
            APIError: If any container creation fails (rolls back all containers)
        """
        bot_path = self.bots_dir / bot_name
        logger.info(f"Creating {shard_count} shard containers for '{bot_name}'")

        # Load base environment variables from .env
        base_env = self._load_bot_env(bot_path)
        base_env['BOT_NAME'] = bot_name

        # Prepare resource limits once
        mem_limit = None
        nano_cpus = None
        if resource_limits:
            if 'memory' in resource_limits:
                mem_limit = resource_limits['memory']
            if 'cpus' in resource_limits:
                nano_cpus = int(resource_limits['cpus'] * 1e9)

        container_ids = []
        created_containers = []  # Track for rollback on failure

        try:
            for shard_id in range(shard_count):
                # Create shard-specific environment
                shard_env = base_env.copy()
                shard_env['SHARD_ID'] = str(shard_id)
                shard_env['SHARD_COUNT'] = str(shard_count)

                # Container naming: multicord_botname_shard_0
                container_name = f"multicord_{bot_name.lower()}_shard_{shard_id}"

                logger.info(f"  Creating shard {shard_id}/{shard_count - 1}: {container_name}")

                # Create container (shared volumes across all shards)
                container = self.docker_client.client.containers.create(
                    image=image_id,
                    name=container_name,
                    environment=shard_env,
                    volumes={
                        str(bot_path / "logs"): {'bind': '/app/logs', 'mode': 'rw'},
                        str(bot_path / "data"): {'bind': '/app/data', 'mode': 'rw'}
                    },
                    network="multicord-network",
                    mem_limit=mem_limit,
                    nano_cpus=nano_cpus,
                    detach=True,
                    labels={
                        "managed-by": "multicord",
                        "bot-name": bot_name,
                        "shard-id": str(shard_id),
                        "shard-count": str(shard_count)
                    }
                )

                created_containers.append(container)
                container_ids.append(container.id)

                logger.info(f"  ✓ Created shard {shard_id}: {container.id[:12]}")

            # Start all containers (after all created successfully)
            for i, container in enumerate(created_containers):
                container.start()
                logger.info(f"  ✓ Started shard {i}")

            logger.info(f"✓ All {shard_count} shard containers running")
            return container_ids

        except APIError as e:
            # Rollback: Remove any containers that were created
            logger.error(f"Failed to create shard containers: {e}")
            logger.info("Rolling back: Removing partially created containers...")

            for container in created_containers:
                try:
                    container.remove(force=True)
                    logger.info(f"  ✓ Removed {container.name}")
                except Exception as cleanup_error:
                    logger.warning(f"  Failed to remove {container.name}: {cleanup_error}")

            raise APIError(f"Shard container creation failed: {e}")

    def _load_bot_env(self, bot_path: Path) -> Dict[str, str]:
        """Load environment variables from bot's .env file."""
        env_file = bot_path / ".env"
        env_vars = {}

        if env_file.exists():
            with open(env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()

        return env_vars

    def start_container(self, container_id: str) -> bool:
        """
        Start existing container.

        Args:
            container_id: Container ID or name

        Returns:
            True if successful

        Raises:
            NotFound: If container not found
            APIError: If start fails
        """
        try:
            container = self.docker_client.client.containers.get(container_id)
            container.start()

            logger.info(f"✓ Started container: {container.name}")
            return True

        except NotFound:
            logger.error(f"Container not found: {container_id}")
            raise
        except APIError as e:
            logger.error(f"Failed to start container: {e}")
            raise

    def stop_container(self, container_id: str, timeout: int = 30) -> bool:
        """
        Gracefully stop container.

        Args:
            container_id: Container ID or name
            timeout: Timeout in seconds before force kill (default: 30)

        Returns:
            True if successful
        """
        try:
            container = self.docker_client.client.containers.get(container_id)
            container.stop(timeout=timeout)

            logger.info(f"✓ Stopped container: {container.name}")
            return True

        except NotFound:
            logger.warning(f"Container not found: {container_id}")
            return False
        except APIError as e:
            logger.error(f"Failed to stop container: {e}")
            return False

    def remove_container(self, container_id: str, force: bool = False) -> bool:
        """
        Remove container.

        Args:
            container_id: Container ID or name
            force: Force removal even if running (default: False)

        Returns:
            True if successful
        """
        try:
            container = self.docker_client.client.containers.get(container_id)
            container.remove(force=force)

            logger.info(f"✓ Removed container: {container.name}")
            return True

        except NotFound:
            logger.warning(f"Container not found: {container_id}")
            return False
        except APIError as e:
            logger.error(f"Failed to remove container: {e}")
            return False

    def get_container_logs(
        self,
        container_id: str,
        follow: bool = False,
        tail: int = 100
    ) -> Generator[str, None, None]:
        """
        Stream logs from container.

        Args:
            container_id: Container ID or name
            follow: Follow log output (stream) (default: False)
            tail: Number of lines from end of logs (default: 100)

        Yields:
            Log lines as strings

        Raises:
            NotFound: If container not found
        """
        try:
            container = self.docker_client.client.containers.get(container_id)

            # Docker SDK expects tail as string ("100", "all")
            tail_str = str(tail) if tail else "all"

            for log_chunk in container.logs(stream=True, follow=follow, tail=tail_str):
                # log_chunk is bytes, decode to string
                if isinstance(log_chunk, bytes):
                    yield log_chunk.decode('utf-8', errors='replace')
                else:
                    # Safety: handle unexpected types
                    yield str(log_chunk)

        except NotFound:
            logger.error(f"Container not found: {container_id}")
            raise

    def get_container_stats(self, container_id: str) -> Dict[str, any]:
        """
        Get container resource statistics.

        Args:
            container_id: Container ID or name

        Returns:
            Dictionary with CPU, memory, network stats

        Raises:
            NotFound: If container not found
        """
        try:
            container = self.docker_client.client.containers.get(container_id)
            stats = container.stats(stream=False)

            # Parse stats
            cpu_percent = self._calculate_cpu_percent(stats)
            memory_usage_mb = stats['memory_stats'].get('usage', 0) / (1024 * 1024)
            memory_limit_mb = stats['memory_stats'].get('limit', 0) / (1024 * 1024)

            # Network stats
            networks = stats.get('networks', {})
            network_rx_bytes = 0
            network_tx_bytes = 0
            for iface_stats in networks.values():
                network_rx_bytes += iface_stats.get('rx_bytes', 0)
                network_tx_bytes += iface_stats.get('tx_bytes', 0)

            return {
                'cpu_percent': round(cpu_percent, 2),
                'memory_mb': round(memory_usage_mb, 2),  # Changed from memory_usage_mb
                'memory_limit_mb': round(memory_limit_mb, 2),
                'memory_percent': round((memory_usage_mb / memory_limit_mb * 100) if memory_limit_mb > 0 else 0, 2),
                'network_rx_mb': round(network_rx_bytes / (1024 * 1024), 2),
                'network_tx_mb': round(network_tx_bytes / (1024 * 1024), 2)
            }

        except NotFound:
            logger.error(f"Container not found: {container_id}")
            raise

    def _calculate_cpu_percent(self, stats: Dict) -> float:
        """Calculate CPU percentage from container stats."""
        cpu_delta = stats['cpu_stats']['cpu_usage']['total_usage'] - \
                    stats['precpu_stats']['cpu_usage']['total_usage']
        system_delta = stats['cpu_stats']['system_cpu_usage'] - \
                       stats['precpu_stats']['system_cpu_usage']

        if system_delta > 0 and cpu_delta > 0:
            cpu_count = len(stats['cpu_stats']['cpu_usage'].get('percpu_usage', [1]))
            return (cpu_delta / system_delta) * cpu_count * 100.0

        return 0.0

    def list_bot_containers(self, bot_name: str) -> List[Container]:
        """
        List all containers for a specific bot.

        Args:
            bot_name: Bot name

        Returns:
            List of Container objects
        """
        all_containers = self.docker_client.list_containers(all_containers=True)
        # Normalize to lowercase for matching (container names are lowercase)
        bot_name_lower = bot_name.lower()
        return [c for c in all_containers if bot_name_lower in c.name.lower()]
